name: Build for Linux
on: 
  push:
  pull_request:
  release:
    types: # This configuration does not affect the page_build event above
      - created
  
jobs:
  build:
    #if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
            submodules: true
      
      - name: Build GCC-stealer
        uses: docker://alpine:edge
        with: 
          args: sh ./build.sh

      - name: Upload binary to artifact
        uses: actions/upload-artifact@master
        with:
          name: GCC-stealer
          path: build/GCC-stealer

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: build
    steps:
        - name: Download GCC-stealer
          uses: actions/download-artifact@v1
          with:
              name: GCC-stealer
        
        - name: Upload GCC-stealer to Github release
          uses: actions/upload-release-asset@v1
          env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{ github.event.release.upload_url }}
              asset_path: GCC-stealer/GCC-stealer
              asset_name: GCC-stealer
              asset_content_type: application/octet-stream